FROM python:3.9-slim

COPY requirements.txt requirements.txt
COPY api/produit_api.py app/produit_api.py

RUN pip install --no-cache-dir -r requirements.txt

WORKDIR /app

CMD ["uvicorn", "produit_api:app", "--host", "0.0.0.0", "--port", "8888"]
