name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Désactive les clones peu profonds pour une meilleure pertinence de l'analyse

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Behave tests with coverage
        run: coverage run -m behave features

      - name: Generate coverage report
        run: coverage xml

      - name: Check xml cat
        run: cat coverage.xml

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_PROJECT_KEY: your_project_key
          SONAR_PROJECT_NAME: your_project_name
          EXTRA_ARGS: '-Dsonar.coverage.reportPaths=coverage.xml'
